### ISSUE TITLE
Also works as a bookmarklet

### ISSUE THREAD

**Issue by tobozo** [bucaran/node-navi#2]
[edit] crunched bookmarklet is lighter
http://ted.mielczarek.org/code/mozilla/bookmarklet.html

    javascript:(function(){var%20builtins=['assert','buffer','child_process','cluster','console','constants','crypto','dgram','dns','domain','events','freelist','fs','http','https','module','net','os','path','punycode','querystring','readline','repl','stream','string_decoder','sys','timers','tls','tty','url','util','vm','zlib','_debugger','_linklist','_stream_duplex','_stream_passthrough','_stream_readable','_stream_transform','_stream_writable'];document.onmouseover=function(e){var%20path=document.querySelector('.final-path');if(!path)return;var%20pkg=e.target.textContent.slice(1,-1),url=pkg,el=e.target;switch(path.textContent){case%20'package.json':case%20'package.cson':case%20'bower.json':el=el.nextSibling&&el.nextSibling.nextSibling;if(!el)return;var%20ver=el.textContent.slice(1,-1);if(ver!=='*'&&!/^[~<>=\^\*]?\d+\.?/.test(ver))return;url='http://ghub.io/'+pkg;break;default:el=el.previousSibling&&el.previousSibling.previousSibling;if(!el||el.textContent!=='require')return;if(~builtins.indexOf(pkg)){url='http://nodejs.org/api/'+pkg+'.html';}else%20if(pkg.indexOf('.')===0){if(pkg!=='./'&&pkg!=='../'){if(!pkg.match(/\.\w+$/))url=pkg+'.js';}}else{url='http://ghub.io/'+pkg.split('/')[0];if(~pkg.indexOf('/')&&pkg.substr(-1)!=='/'){url=url+'/'+'blob/master/'+pkg.split('/')[1];}}}e.target.innerHTML=e.target.innerHTML%20.replace(pkg,'<a%20class="pl-pds"%20href="'+url+'">'+pkg+'</a>');};})();

**Comment by bucaran** [comment]
The snippet does not work for me though. 

I guess it is working for you, so would you mind describing what you did to make it work?

Thanks!

**Comment by bucaran** [comment]
@tobozo

**Comment by tobozo** [comment]
Firefox / View / Toolbars / enable Bookmark Toolbar 
Scenario 1 :  Right clik on the bookmark toolbar -> new bookmark / paste the code in the 'location' part, name it, save it
Scenario 2 : use the code inside <a href> on a document, drag the link onto your bookmark toolbar

Note : in all cases it must be run from the bookmark toolbar, not from the bookmark menu.

**Comment by bucaran** [comment]
That's what I did.

__It works with the new link you provided though__.

**Comment by bucaran** [comment]
### Instructions for Safari

1. Copy [the raw code](https://raw.githubusercontent.com/bucaran/node-navi/master/node-navi.safariextension/src/node-navi.js).
2. [Crunch it with this tool](http://ted.mielczarek.org/code/mozilla/bookmarklet.html) and copy the generated script.
3. `Cmd+D` to add a new bookmark; enter the _name_ of the bookmarklet. e.g., __node-navi__.
4. `Alt+Cmd+B` to edit bookmarks in Safari.
5. Select the new bookmark and edit the URL and paste the previously generated script.
6. `Cmd+Shift+B` to toggle the favorites bar and click the new link.
